name: Geekulcha Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  imageName : geekulchademo
  tag : '${{ github.run_id  }}'
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${{ secrets.DOCKER_REGISTRY }}/${{ env.imageName }}:${{ env.tag }}" --tag "${{ secrets.DOCKER_REGISTRY }}/${{ env.imageName }}:latest"

    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      uses: docker/login-action@v1.10.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ secrets.DOCKER_REGISTRY }}
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PWD }}
        # Log out from the Docker registry at the end of a job
        logout: false

    - name: Build the Docker image
      run: | 
        docker push "${{ secrets.DOCKER_REGISTRY }}/${{ env.imageName }}:${{ env.tag }}" 
        docker push "${{ secrets.DOCKER_REGISTRY }}/${{ env.imageName }}:latest"
